### ISSUE TITLE
auto-update of putlockertv 3.0.1 is failing

### ISSUE THREAD

**Issue by misty-** [bunkford/Bunkford#4]
Found plugin.video.putlockertv-3.0.1.zip contains hidden folder and file which cause xbmc / kodi to report incorrect structure. Upon unzipping the above file on a Windows PC to investigate. The folder structure is:
plugin.video.putlockertv-3.0.1
--> __MACOSX  (This causes structure failure)
--> plugin.video.putlockertv

Within the extracted plugin.video.putlockertv folder is .DS_Store which causes structure failure.
Even after removing the offending folder / file, the addon continues to fail updating.
Found the cause to be in addon.xml file. The version number 3.0.1 is enclosed by smart quotes. These should be replaced with plain quotes. After making changes and zipping the plugin.video.putlockertv folder and renaming to plugin.video.putlockertv-3.0.1.zip, install from zip works correctly, though update through the repo continues to fail in xbmc / kodi.

**Comment by oomasoo** [comment]
When you check the version number of the update in kodi it show  "3.0.1"  and not just 3.0.1
